### ISSUE TITLE
Handle special characters

### ISSUE THREAD

**Issue by LaiKash** [changkun/rmtrash#2]
Hello, first of all great port! The only problem I am having is that it is not working with special characters such as *

How can we "rmthrash" all the files in a directory without having to delete them one by one, for example?

Thanks!

**Comment by changkun** [comment]
Hi, Thanks for reporting your user experiences.

I've just released a version 0.0.3 that now `rmtrash` can work with wildcard, which you can install from the following command:

```
go install changkun.de/x/rmtrash@v0.0.3
```

Please let me know if the latest version works for your reported case or not.

**Comment by LaiKash** [comment]
Wow, that was fast, I was going to do a pull request after work... Working perfectly now, thanks a lot!!!

**Comment by changkun** [comment]
Sounds great, thank you very much for the confirmation :)


Close as it is solved in [`changkun.de/x/rmtrash@v0.0.3`](https://github.com/changkun/rmtrash/releases/tag/v0.0.3).
