### ISSUE TITLE
installing executables with 'go get' in module mode is deprecated

### ISSUE THREAD

**Issue by manish-makwana** [changkun/rmtrash#3]
Hello,

installing with the latest version of golang (via homebrew) shows the above error. I suggest the installation line be updated to the following:

`go install changkun.de/x/rmtrash@latest`

Also, I've never used Go before and it took me a while to get everything working. I did the following - could be worth adding to the readme for other n00bs:

1. Run `brew install golang`
2. Add to `$/.bash_profile`: `export PATH=$PATH:$HOME/go/bin`
3. Run `source ~/.bash_profile`
4. Setup the alias.

Thanks for making this tool! Just got around to sorting out some homebrew warnings I'd been ignoring for a while. Not how I expected to spend my Friday evening haha...

**Comment by changkun** [comment]
Hi, thanks for reporting the installation experience. I've documented the latest installation guide.
